window.NOVA_CATALOG = [
  {brand:'HONOR', name:'Magic8 Lite', memory:'8 GB / 256 GB', price:4120, stock:5, image:'magic.jpg', accent:'#d40020', cpu:'Snapdragon 6 Gen 4', main:'108 MP con OIS + 5 MP ultra gran angular', front:'16 MP', battery:'8.300 mAh · SuperCharge 66 W', display:'AMOLED · 120 Hz', resistance:'IP68 · IP69 · IP69K', highlight:'Récord Guinness: caída de smartphone a 6,133 m.', verified:true},
  {brand:'HONOR', name:'X7E', memory:'6 GB / 256 GB', price:2550, stock:7, image:'x7e.jpg' , accent:'#6a0d1d', cpu:'Pendiente de verificación', main:'Pendiente de verificación', front:'Pendiente de verificación', battery:'Pendiente de verificación', display:'Pendiente de verificación', resistance:'Consultar ficha oficial', verified:false},
  {brand:'HONOR', name:'X5C Plus', memory:'6 GB / 256 GB', price:1830, stock:12,  image:'x5cplus.jpg' , accent:'#a21b32', cpu:'Pendiente de verificación', main:'Pendiente de verificación', front:'Pendiente de verificación', battery:'Pendiente de verificación', display:'Pendiente de verificación', resistance:'Consultar ficha oficial', verified:false},
  {brand:'INFINIX', name:'Smart 20', memory:'4 GB / 128 GB', price:1280, stock:15, image: accent:'smart20.jpg' ,'#151515', cpu:'Pendiente de verificación', main:'Pendiente de verificación', front:'Pendiente de verificación', battery:'Pendiente de verificación', display:'Pendiente de verificación', resistance:'Consultar ficha oficial', verified:false},
  {brand:'INFINIX', name:'Hot 60 Pro+', memory:'8 GB / 256 GB', price:2530, stock:6, accent:'#d40020', cpu:'Pendiente de verificación', main:'Pendiente de verificación', front:'Pendiente de verificación', battery:'Pendiente de verificación', display:'Pendiente de verificación', resistance:'Consultar ficha oficial', verified:false},
  {brand:'SAMSUNG', name:'Galaxy A16', memory:'4 GB / 128 GB', price:1740, stock:9, accent:'#111111', cpu:'Octa-core hasta 2,2 GHz', main:'50 MP + 5 MP + 2 MP', front:'13 MP', battery:'5.000 mAh', display:'6,7″ Super AMOLED · FHD+', resistance:'Consultar ficha oficial', verified:true},
  {brand:'SAMSUNG', name:'Galaxy A07', memory:'4 GB / 128 GB', price:1520, stock:11, accent:'#d40020', cpu:'Pendiente de verificación', main:'Pendiente de verificación', front:'Pendiente de verificación', battery:'Pendiente de verificación', display:'Pendiente de verificación', resistance:'Consultar ficha oficial', verified:false},
  {brand:'TECNO', name:'Spark Go3', memory:'4 GB / 128 GB', price:1270, stock:13, accent:'#111111', cpu:'Pendiente de verificación', main:'Pendiente de verificación', front:'Pendiente de verificación', battery:'Pendiente de verificación', display:'Pendiente de verificación', resistance:'Consultar ficha oficial', verified:false},
  {brand:'TECNO', name:'Pova 7 4G', memory:'8 GB / 256 GB', price:2430, stock:8, accent:'#d40020', cpu:'Pendiente de verificación', main:'Pendiente de verificación', front:'Pendiente de verificación', battery:'Pendiente de verificación', display:'Pendiente de verificación', resistance:'Consultar ficha oficial', verified:false},
  {brand:'XIAOMI', name:'Redmi Note 15 5G', memory:'6 GB / 128 GB', price:2130, stock:10, accent:'#111111', cpu:'Snapdragon 6 Gen 3', main:'108 MP + 8 MP ultra gran angular', front:'20 MP', battery:'5.520 mAh · carga turbo 45 W', display:'6,67″ AMOLED · 120 Hz', resistance:'IP66', highlight:'Cámara principal con video 4K y OIS según mercado.', verified:true},
  {brand:'XIAOMI', name:'Redmi A7 Pro', memory:'4 GB / 128 GB', price:1340, stock:14, accent:'#d40020', cpu:'Pendiente de verificación', main:'Pendiente de verificación', front:'Pendiente de verificación', battery:'Pendiente de verificación', display:'Pendiente de verificación', resistance:'Consultar ficha oficial', verified:false}
];
